//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBFRM.Areas.ComplainManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EDWEntities : DbContext
    {
        public EDWEntities()
            : base("name=EDWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vDonor_Name> vDonor_Name { get; set; }
        public virtual DbSet<vFieldSite> vFieldSite { get; set; }
        public virtual DbSet<vSex> vSex { get; set; }
        public virtual DbSet<vCommunicationMethod> vCommunicationMethod { get; set; }
        public virtual DbSet<vCommunicationStage> vCommunicationStage { get; set; }
        public virtual DbSet<vCommunityBasedComplaintDocumentation> vCommunityBasedComplaintDocumentation { get; set; }
        public virtual DbSet<vCommunityBasedComplaintLocation> vCommunityBasedComplaintLocation { get; set; }
        public virtual DbSet<vComplaintAppeal> vComplaintAppeal { get; set; }
        public virtual DbSet<vComplaintAppealCommittee> vComplaintAppealCommittee { get; set; }
        public virtual DbSet<vComplaintCategory> vComplaintCategory { get; set; }
        public virtual DbSet<vComplaintCommunication> vComplaintCommunication { get; set; }
        public virtual DbSet<vComplaintResolution> vComplaintResolution { get; set; }
        public virtual DbSet<vComplaintStatus> vComplaintStatus { get; set; }
        public virtual DbSet<vExternalReferral> vExternalReferral { get; set; }
        public virtual DbSet<vLanguageDialect> vLanguageDialect { get; set; }
        public virtual DbSet<vPersonVulnerabilityType> vPersonVulnerabilityType { get; set; }
        public virtual DbSet<vUserManager> vUserManager { get; set; }
        public virtual DbSet<vCommunityBasedComplaintFieldSector> vCommunityBasedComplaintFieldSector { get; set; }
        public virtual DbSet<vComplainantVulnerability> vComplainantVulnerability { get; set; }
        public virtual DbSet<vComplaintClassification> vComplaintClassification { get; set; }
        public virtual DbSet<vCommunityBasedComplaint> vCommunityBasedComplaint { get; set; }
        public virtual DbSet<vComplainantDetail> vComplainantDetail { get; set; }
    
        public virtual ObjectResult<spGetvCommunicationMethod_Result> spGetvCommunicationMethod()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvCommunicationMethod_Result>("spGetvCommunicationMethod");
        }
    
        public virtual ObjectResult<spGetvCommunicationStage_Result> spGetvCommunicationStage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvCommunicationStage_Result>("spGetvCommunicationStage");
        }
    
        public virtual ObjectResult<spGetvDonor_Name_Result> spGetvDonor_Name()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvDonor_Name_Result>("spGetvDonor_Name");
        }
    
        public virtual ObjectResult<spGetvvUserDetails_Result> spGetvvUserDetails(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvvUserDetails_Result>("spGetvvUserDetails", userNameParameter);
        }
    
        public virtual ObjectResult<spGetvUserManager_Result> spGetvUserManager(Nullable<long> eDWPersonID)
        {
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvUserManager_Result>("spGetvUserManager", eDWPersonIDParameter);
        }
    
        public virtual ObjectResult<spGetvSearchUser_Result> spGetvSearchUser(string fullName)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvSearchUser_Result>("spGetvSearchUser", fullNameParameter);
        }
    
        public virtual ObjectResult<spGetvUserAssign_Result> spGetvUserAssign()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvUserAssign_Result>("spGetvUserAssign");
        }
    
        public virtual ObjectResult<spGetPersonVulnerabilityType_Result> spGetPersonVulnerabilityType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPersonVulnerabilityType_Result>("spGetPersonVulnerabilityType");
        }
    
        public virtual ObjectResult<spGetvGender_Result> spGetvGender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvGender_Result>("spGetvGender");
        }
    
        public virtual ObjectResult<spGetvLanguageDialect_Result> spGetvLanguageDialect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvLanguageDialect_Result>("spGetvLanguageDialect");
        }
    
        public virtual ObjectResult<spGetvComplaintCategory_Result> spGetvComplaintCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvComplaintCategory_Result>("spGetvComplaintCategory");
        }
    
        public virtual ObjectResult<spGetvUserAssign2_Result> spGetvUserAssign2(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvUserAssign2_Result>("spGetvUserAssign2", userNameParameter);
        }
    
        public virtual ObjectResult<spGetvFieldSector_Result> spGetvFieldSector()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvFieldSector_Result>("spGetvFieldSector");
        }
    
        public virtual ObjectResult<spGetvCommunicationMethodGenral_Result> spGetvCommunicationMethodGenral()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvCommunicationMethodGenral_Result>("spGetvCommunicationMethodGenral");
        }
    
        public virtual int spGetCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetCountries");
        }
    
        public virtual ObjectResult<spGetCountry_Result> spGetCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCountry_Result>("spGetCountry");
        }
    
        public virtual ObjectResult<spGetReferralType_Result> spGetReferralType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetReferralType_Result>("spGetReferralType");
        }
    
        public virtual ObjectResult<spGetComplainClassification_Result> spGetComplainClassification()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetComplainClassification_Result>("spGetComplainClassification");
        }
    
        public virtual ObjectResult<spGetReferrallevel_Result> spGetReferrallevel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetReferrallevel_Result>("spGetReferrallevel");
        }
    
        public virtual ObjectResult<spGetvCommunicationMethodEthics_Result> spGetvCommunicationMethodEthics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvCommunicationMethodEthics_Result>("spGetvCommunicationMethodEthics");
        }
    
        public virtual ObjectResult<spGetCategoryByID_Result> spGetCategoryByID(Nullable<byte> complaintCategoryID)
        {
            var complaintCategoryIDParameter = complaintCategoryID.HasValue ?
                new ObjectParameter("ComplaintCategoryID", complaintCategoryID) :
                new ObjectParameter("ComplaintCategoryID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCategoryByID_Result>("spGetCategoryByID", complaintCategoryIDParameter);
        }
    
        public virtual ObjectResult<spGetComplaintStatus_Result> spGetComplaintStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetComplaintStatus_Result>("spGetComplaintStatus");
        }
    
        public virtual ObjectResult<spInsert_vCBCDocumentation_Result> spInsert_vCBCDocumentation(Nullable<int> communityBasedComplaintID, string documentHyperlink, string supportingDocumentDescription, string updateUser, Nullable<bool> appealDocumentFlag)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var documentHyperlinkParameter = documentHyperlink != null ?
                new ObjectParameter("DocumentHyperlink", documentHyperlink) :
                new ObjectParameter("DocumentHyperlink", typeof(string));
    
            var supportingDocumentDescriptionParameter = supportingDocumentDescription != null ?
                new ObjectParameter("SupportingDocumentDescription", supportingDocumentDescription) :
                new ObjectParameter("SupportingDocumentDescription", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            var appealDocumentFlagParameter = appealDocumentFlag.HasValue ?
                new ObjectParameter("AppealDocumentFlag", appealDocumentFlag) :
                new ObjectParameter("AppealDocumentFlag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spInsert_vCBCDocumentation_Result>("spInsert_vCBCDocumentation", communityBasedComplaintIDParameter, documentHyperlinkParameter, supportingDocumentDescriptionParameter, updateUserParameter, appealDocumentFlagParameter);
        }
    
        public virtual ObjectResult<spInsert_vCBCDocumentationAppeal_Result> spInsert_vCBCDocumentationAppeal(Nullable<int> communityBasedComplaintID, string documentHyperlink, string supportingDocumentDescription, Nullable<bool> appealDocumentFlag, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var documentHyperlinkParameter = documentHyperlink != null ?
                new ObjectParameter("DocumentHyperlink", documentHyperlink) :
                new ObjectParameter("DocumentHyperlink", typeof(string));
    
            var supportingDocumentDescriptionParameter = supportingDocumentDescription != null ?
                new ObjectParameter("SupportingDocumentDescription", supportingDocumentDescription) :
                new ObjectParameter("SupportingDocumentDescription", typeof(string));
    
            var appealDocumentFlagParameter = appealDocumentFlag.HasValue ?
                new ObjectParameter("AppealDocumentFlag", appealDocumentFlag) :
                new ObjectParameter("AppealDocumentFlag", typeof(bool));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spInsert_vCBCDocumentationAppeal_Result>("spInsert_vCBCDocumentationAppeal", communityBasedComplaintIDParameter, documentHyperlinkParameter, supportingDocumentDescriptionParameter, appealDocumentFlagParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCAcknowledgement_Result> spSave_CBCAcknowledgement(Nullable<int> communityBasedComplaintID, Nullable<int> eDWPersonID, Nullable<System.DateTime> communicationDate, Nullable<byte> communicationStageID, Nullable<byte> communicationMethodID, string comment, string otherComplaintCommunicationMethodText, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var communicationDateParameter = communicationDate.HasValue ?
                new ObjectParameter("CommunicationDate", communicationDate) :
                new ObjectParameter("CommunicationDate", typeof(System.DateTime));
    
            var communicationStageIDParameter = communicationStageID.HasValue ?
                new ObjectParameter("CommunicationStageID", communicationStageID) :
                new ObjectParameter("CommunicationStageID", typeof(byte));
    
            var communicationMethodIDParameter = communicationMethodID.HasValue ?
                new ObjectParameter("CommunicationMethodID", communicationMethodID) :
                new ObjectParameter("CommunicationMethodID", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var otherComplaintCommunicationMethodTextParameter = otherComplaintCommunicationMethodText != null ?
                new ObjectParameter("OtherComplaintCommunicationMethodText", otherComplaintCommunicationMethodText) :
                new ObjectParameter("OtherComplaintCommunicationMethodText", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCAcknowledgement_Result>("spSave_CBCAcknowledgement", communityBasedComplaintIDParameter, eDWPersonIDParameter, communicationDateParameter, communicationStageIDParameter, communicationMethodIDParameter, commentParameter, otherComplaintCommunicationMethodTextParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCExternalReferral_Result> spSave_CBCExternalReferral(Nullable<int> communityBasedComplaintID, Nullable<System.DateTime> referralDate, string referralAgencyName, string referralPersonName, string referralPersonPositionText, string contactComment, string hQDisclosureAuthorizationText, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var referralDateParameter = referralDate.HasValue ?
                new ObjectParameter("ReferralDate", referralDate) :
                new ObjectParameter("ReferralDate", typeof(System.DateTime));
    
            var referralAgencyNameParameter = referralAgencyName != null ?
                new ObjectParameter("ReferralAgencyName", referralAgencyName) :
                new ObjectParameter("ReferralAgencyName", typeof(string));
    
            var referralPersonNameParameter = referralPersonName != null ?
                new ObjectParameter("ReferralPersonName", referralPersonName) :
                new ObjectParameter("ReferralPersonName", typeof(string));
    
            var referralPersonPositionTextParameter = referralPersonPositionText != null ?
                new ObjectParameter("ReferralPersonPositionText", referralPersonPositionText) :
                new ObjectParameter("ReferralPersonPositionText", typeof(string));
    
            var contactCommentParameter = contactComment != null ?
                new ObjectParameter("ContactComment", contactComment) :
                new ObjectParameter("ContactComment", typeof(string));
    
            var hQDisclosureAuthorizationTextParameter = hQDisclosureAuthorizationText != null ?
                new ObjectParameter("HQDisclosureAuthorizationText", hQDisclosureAuthorizationText) :
                new ObjectParameter("HQDisclosureAuthorizationText", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCExternalReferral_Result>("spSave_CBCExternalReferral", communityBasedComplaintIDParameter, referralDateParameter, referralAgencyNameParameter, referralPersonNameParameter, referralPersonPositionTextParameter, contactCommentParameter, hQDisclosureAuthorizationTextParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCInternalReferralCountryLevel_Result> spSave_CBCInternalReferralCountryLevel(Nullable<int> communityBasedComplaintID, Nullable<int> eDWPersonID, Nullable<System.DateTime> communicationDate, Nullable<byte> communicationStageID, string comment, Nullable<bool> fromPersonFlag, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var communicationDateParameter = communicationDate.HasValue ?
                new ObjectParameter("CommunicationDate", communicationDate) :
                new ObjectParameter("CommunicationDate", typeof(System.DateTime));
    
            var communicationStageIDParameter = communicationStageID.HasValue ?
                new ObjectParameter("CommunicationStageID", communicationStageID) :
                new ObjectParameter("CommunicationStageID", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var fromPersonFlagParameter = fromPersonFlag.HasValue ?
                new ObjectParameter("FromPersonFlag", fromPersonFlag) :
                new ObjectParameter("FromPersonFlag", typeof(bool));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCInternalReferralCountryLevel_Result>("spSave_CBCInternalReferralCountryLevel", communityBasedComplaintIDParameter, eDWPersonIDParameter, communicationDateParameter, communicationStageIDParameter, commentParameter, fromPersonFlagParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCInternalReferralHQLevel_Result> spSave_CBCInternalReferralHQLevel(Nullable<int> communityBasedComplaintID, Nullable<int> eDWPersonID, Nullable<System.DateTime> communicationDate, Nullable<byte> communicationStageID, Nullable<byte> communicationMethodID, string comment, string otherComplaintCommunicationMethodText, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var communicationDateParameter = communicationDate.HasValue ?
                new ObjectParameter("CommunicationDate", communicationDate) :
                new ObjectParameter("CommunicationDate", typeof(System.DateTime));
    
            var communicationStageIDParameter = communicationStageID.HasValue ?
                new ObjectParameter("CommunicationStageID", communicationStageID) :
                new ObjectParameter("CommunicationStageID", typeof(byte));
    
            var communicationMethodIDParameter = communicationMethodID.HasValue ?
                new ObjectParameter("CommunicationMethodID", communicationMethodID) :
                new ObjectParameter("CommunicationMethodID", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var otherComplaintCommunicationMethodTextParameter = otherComplaintCommunicationMethodText != null ?
                new ObjectParameter("OtherComplaintCommunicationMethodText", otherComplaintCommunicationMethodText) :
                new ObjectParameter("OtherComplaintCommunicationMethodText", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCInternalReferralHQLevel_Result>("spSave_CBCInternalReferralHQLevel", communityBasedComplaintIDParameter, eDWPersonIDParameter, communicationDateParameter, communicationStageIDParameter, communicationMethodIDParameter, commentParameter, otherComplaintCommunicationMethodTextParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCLocation_Result> spSave_CBCLocation(Nullable<int> communityBasedComplaintID, string locationText, string communityText, string districtText, string provinceText, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var locationTextParameter = locationText != null ?
                new ObjectParameter("LocationText", locationText) :
                new ObjectParameter("LocationText", typeof(string));
    
            var communityTextParameter = communityText != null ?
                new ObjectParameter("CommunityText", communityText) :
                new ObjectParameter("CommunityText", typeof(string));
    
            var districtTextParameter = districtText != null ?
                new ObjectParameter("DistrictText", districtText) :
                new ObjectParameter("DistrictText", typeof(string));
    
            var provinceTextParameter = provinceText != null ?
                new ObjectParameter("ProvinceText", provinceText) :
                new ObjectParameter("ProvinceText", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCLocation_Result>("spSave_CBCLocation", communityBasedComplaintIDParameter, locationTextParameter, communityTextParameter, districtTextParameter, provinceTextParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCResolution_Result> spSave_CBCResolution(Nullable<int> communityBasedComplaintID, string investigationDescription, string investigationPointOfContactName, string correctiveActionDescription, Nullable<System.DateTime> resolutionDate, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var investigationDescriptionParameter = investigationDescription != null ?
                new ObjectParameter("InvestigationDescription", investigationDescription) :
                new ObjectParameter("InvestigationDescription", typeof(string));
    
            var investigationPointOfContactNameParameter = investigationPointOfContactName != null ?
                new ObjectParameter("InvestigationPointOfContactName", investigationPointOfContactName) :
                new ObjectParameter("InvestigationPointOfContactName", typeof(string));
    
            var correctiveActionDescriptionParameter = correctiveActionDescription != null ?
                new ObjectParameter("CorrectiveActionDescription", correctiveActionDescription) :
                new ObjectParameter("CorrectiveActionDescription", typeof(string));
    
            var resolutionDateParameter = resolutionDate.HasValue ?
                new ObjectParameter("ResolutionDate", resolutionDate) :
                new ObjectParameter("ResolutionDate", typeof(System.DateTime));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCResolution_Result>("spSave_CBCResolution", communityBasedComplaintIDParameter, investigationDescriptionParameter, investigationPointOfContactNameParameter, correctiveActionDescriptionParameter, resolutionDateParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCResponse_Result> spSave_CBCResponse(Nullable<int> communityBasedComplaintID, Nullable<int> eDWPersonID, Nullable<System.DateTime> communicationDate, Nullable<byte> communicationStageID, Nullable<byte> communicationMethodID, string comment, string otherComplaintCommunicationMethodText, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var communicationDateParameter = communicationDate.HasValue ?
                new ObjectParameter("CommunicationDate", communicationDate) :
                new ObjectParameter("CommunicationDate", typeof(System.DateTime));
    
            var communicationStageIDParameter = communicationStageID.HasValue ?
                new ObjectParameter("CommunicationStageID", communicationStageID) :
                new ObjectParameter("CommunicationStageID", typeof(byte));
    
            var communicationMethodIDParameter = communicationMethodID.HasValue ?
                new ObjectParameter("CommunicationMethodID", communicationMethodID) :
                new ObjectParameter("CommunicationMethodID", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var otherComplaintCommunicationMethodTextParameter = otherComplaintCommunicationMethodText != null ?
                new ObjectParameter("OtherComplaintCommunicationMethodText", otherComplaintCommunicationMethodText) :
                new ObjectParameter("OtherComplaintCommunicationMethodText", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCResponse_Result>("spSave_CBCResponse", communityBasedComplaintIDParameter, eDWPersonIDParameter, communicationDateParameter, communicationStageIDParameter, communicationMethodIDParameter, commentParameter, otherComplaintCommunicationMethodTextParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_ComplaintAppeal_Result> spSave_ComplaintAppeal(Nullable<int> communityBasedComplaintID, Nullable<System.DateTime> appealDate, string processDescription, Nullable<byte> appealReceivedCommunicationMethodID, string otherComplaintCommunicationMethodText, string appealResolutionDescription, Nullable<System.DateTime> appealResolutionDate, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var appealDateParameter = appealDate.HasValue ?
                new ObjectParameter("AppealDate", appealDate) :
                new ObjectParameter("AppealDate", typeof(System.DateTime));
    
            var processDescriptionParameter = processDescription != null ?
                new ObjectParameter("ProcessDescription", processDescription) :
                new ObjectParameter("ProcessDescription", typeof(string));
    
            var appealReceivedCommunicationMethodIDParameter = appealReceivedCommunicationMethodID.HasValue ?
                new ObjectParameter("AppealReceivedCommunicationMethodID", appealReceivedCommunicationMethodID) :
                new ObjectParameter("AppealReceivedCommunicationMethodID", typeof(byte));
    
            var otherComplaintCommunicationMethodTextParameter = otherComplaintCommunicationMethodText != null ?
                new ObjectParameter("OtherComplaintCommunicationMethodText", otherComplaintCommunicationMethodText) :
                new ObjectParameter("OtherComplaintCommunicationMethodText", typeof(string));
    
            var appealResolutionDescriptionParameter = appealResolutionDescription != null ?
                new ObjectParameter("AppealResolutionDescription", appealResolutionDescription) :
                new ObjectParameter("AppealResolutionDescription", typeof(string));
    
            var appealResolutionDateParameter = appealResolutionDate.HasValue ?
                new ObjectParameter("AppealResolutionDate", appealResolutionDate) :
                new ObjectParameter("AppealResolutionDate", typeof(System.DateTime));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_ComplaintAppeal_Result>("spSave_ComplaintAppeal", communityBasedComplaintIDParameter, appealDateParameter, processDescriptionParameter, appealReceivedCommunicationMethodIDParameter, otherComplaintCommunicationMethodTextParameter, appealResolutionDescriptionParameter, appealResolutionDateParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_vComplainantDetail_Result> spSave_vComplainantDetail(Nullable<int> eDWComplainantID, Nullable<int> communityBasedComplaintID, Nullable<byte> ageYearNumber, string primaryLanguageDialectCode, string sexCode, string personName, string addressText, string phoneNumber, string emailAddress, string complainantProgramRelationshipText, string otherCommunicationAvenueText, string otherLanguageDialectText, Nullable<bool> complainantAllowContactFlag, Nullable<bool> complainantAllowVisitFlag, Nullable<bool> complainantQuestionsAddressedFlag, Nullable<bool> followUpContactDetailsFlag, Nullable<bool> handlingProcessExplainedFlag, Nullable<bool> processTimelineDiscussedFlag, Nullable<bool> responseReceivalExplainedFlag, string updateUser)
        {
            var eDWComplainantIDParameter = eDWComplainantID.HasValue ?
                new ObjectParameter("EDWComplainantID", eDWComplainantID) :
                new ObjectParameter("EDWComplainantID", typeof(int));
    
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var ageYearNumberParameter = ageYearNumber.HasValue ?
                new ObjectParameter("AgeYearNumber", ageYearNumber) :
                new ObjectParameter("AgeYearNumber", typeof(byte));
    
            var primaryLanguageDialectCodeParameter = primaryLanguageDialectCode != null ?
                new ObjectParameter("PrimaryLanguageDialectCode", primaryLanguageDialectCode) :
                new ObjectParameter("PrimaryLanguageDialectCode", typeof(string));
    
            var sexCodeParameter = sexCode != null ?
                new ObjectParameter("SexCode", sexCode) :
                new ObjectParameter("SexCode", typeof(string));
    
            var personNameParameter = personName != null ?
                new ObjectParameter("PersonName", personName) :
                new ObjectParameter("PersonName", typeof(string));
    
            var addressTextParameter = addressText != null ?
                new ObjectParameter("AddressText", addressText) :
                new ObjectParameter("AddressText", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var complainantProgramRelationshipTextParameter = complainantProgramRelationshipText != null ?
                new ObjectParameter("ComplainantProgramRelationshipText", complainantProgramRelationshipText) :
                new ObjectParameter("ComplainantProgramRelationshipText", typeof(string));
    
            var otherCommunicationAvenueTextParameter = otherCommunicationAvenueText != null ?
                new ObjectParameter("OtherCommunicationAvenueText", otherCommunicationAvenueText) :
                new ObjectParameter("OtherCommunicationAvenueText", typeof(string));
    
            var otherLanguageDialectTextParameter = otherLanguageDialectText != null ?
                new ObjectParameter("OtherLanguageDialectText", otherLanguageDialectText) :
                new ObjectParameter("OtherLanguageDialectText", typeof(string));
    
            var complainantAllowContactFlagParameter = complainantAllowContactFlag.HasValue ?
                new ObjectParameter("ComplainantAllowContactFlag", complainantAllowContactFlag) :
                new ObjectParameter("ComplainantAllowContactFlag", typeof(bool));
    
            var complainantAllowVisitFlagParameter = complainantAllowVisitFlag.HasValue ?
                new ObjectParameter("ComplainantAllowVisitFlag", complainantAllowVisitFlag) :
                new ObjectParameter("ComplainantAllowVisitFlag", typeof(bool));
    
            var complainantQuestionsAddressedFlagParameter = complainantQuestionsAddressedFlag.HasValue ?
                new ObjectParameter("ComplainantQuestionsAddressedFlag", complainantQuestionsAddressedFlag) :
                new ObjectParameter("ComplainantQuestionsAddressedFlag", typeof(bool));
    
            var followUpContactDetailsFlagParameter = followUpContactDetailsFlag.HasValue ?
                new ObjectParameter("FollowUpContactDetailsFlag", followUpContactDetailsFlag) :
                new ObjectParameter("FollowUpContactDetailsFlag", typeof(bool));
    
            var handlingProcessExplainedFlagParameter = handlingProcessExplainedFlag.HasValue ?
                new ObjectParameter("HandlingProcessExplainedFlag", handlingProcessExplainedFlag) :
                new ObjectParameter("HandlingProcessExplainedFlag", typeof(bool));
    
            var processTimelineDiscussedFlagParameter = processTimelineDiscussedFlag.HasValue ?
                new ObjectParameter("ProcessTimelineDiscussedFlag", processTimelineDiscussedFlag) :
                new ObjectParameter("ProcessTimelineDiscussedFlag", typeof(bool));
    
            var responseReceivalExplainedFlagParameter = responseReceivalExplainedFlag.HasValue ?
                new ObjectParameter("ResponseReceivalExplainedFlag", responseReceivalExplainedFlag) :
                new ObjectParameter("ResponseReceivalExplainedFlag", typeof(bool));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_vComplainantDetail_Result>("spSave_vComplainantDetail", eDWComplainantIDParameter, communityBasedComplaintIDParameter, ageYearNumberParameter, primaryLanguageDialectCodeParameter, sexCodeParameter, personNameParameter, addressTextParameter, phoneNumberParameter, emailAddressParameter, complainantProgramRelationshipTextParameter, otherCommunicationAvenueTextParameter, otherLanguageDialectTextParameter, complainantAllowContactFlagParameter, complainantAllowVisitFlagParameter, complainantQuestionsAddressedFlagParameter, followUpContactDetailsFlagParameter, handlingProcessExplainedFlagParameter, processTimelineDiscussedFlagParameter, responseReceivalExplainedFlagParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCFieldSector_Result> spSave_CBCFieldSector(Nullable<int> communityBasedComplaintID, string fieldSectorCode, string otherSectorText)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var fieldSectorCodeParameter = fieldSectorCode != null ?
                new ObjectParameter("FieldSectorCode", fieldSectorCode) :
                new ObjectParameter("FieldSectorCode", typeof(string));
    
            var otherSectorTextParameter = otherSectorText != null ?
                new ObjectParameter("OtherSectorText", otherSectorText) :
                new ObjectParameter("OtherSectorText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCFieldSector_Result>("spSave_CBCFieldSector", communityBasedComplaintIDParameter, fieldSectorCodeParameter, otherSectorTextParameter);
        }
    
        public virtual ObjectResult<spSave_CBCVulnerability_Result> spSave_CBCVulnerability(Nullable<int> eDWComplainantID, Nullable<byte> vulnerabilityTypeID)
        {
            var eDWComplainantIDParameter = eDWComplainantID.HasValue ?
                new ObjectParameter("EDWComplainantID", eDWComplainantID) :
                new ObjectParameter("EDWComplainantID", typeof(int));
    
            var vulnerabilityTypeIDParameter = vulnerabilityTypeID.HasValue ?
                new ObjectParameter("VulnerabilityTypeID", vulnerabilityTypeID) :
                new ObjectParameter("VulnerabilityTypeID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCVulnerability_Result>("spSave_CBCVulnerability", eDWComplainantIDParameter, vulnerabilityTypeIDParameter);
        }
    
        public virtual ObjectResult<spSave_CBFAppealCommittee_Result> spSave_CBFAppealCommittee(Nullable<int> communityBasedComplaintID, Nullable<int> eDWPersonID, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBFAppealCommittee_Result>("spSave_CBFAppealCommittee", communityBasedComplaintIDParameter, eDWPersonIDParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spGetvProject_Name_Result> spGetvProject_Name()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvProject_Name_Result>("spGetvProject_Name");
        }
    
        public virtual ObjectResult<spGetCategoryRefral_Result> spGetCategoryRefral(Nullable<byte> classificationID)
        {
            var classificationIDParameter = classificationID.HasValue ?
                new ObjectParameter("ClassificationID", classificationID) :
                new ObjectParameter("ClassificationID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCategoryRefral_Result>("spGetCategoryRefral", classificationIDParameter);
        }
    
        public virtual ObjectResult<spDelete_CBFFieldSector_Result> spDelete_CBFFieldSector(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFFieldSector_Result>("spDelete_CBFFieldSector", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spDelete_CBFAppealCommittee_Result> spDelete_CBFAppealCommittee(Nullable<int> communityBasedComplaintID, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFAppealCommittee_Result>("spDelete_CBFAppealCommittee", communityBasedComplaintIDParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spDelete_CBFVulnerability_Result> spDelete_CBFVulnerability(Nullable<int> eDWComplainantID)
        {
            var eDWComplainantIDParameter = eDWComplainantID.HasValue ?
                new ObjectParameter("EDWComplainantID", eDWComplainantID) :
                new ObjectParameter("EDWComplainantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFVulnerability_Result>("spDelete_CBFVulnerability", eDWComplainantIDParameter);
        }
    
        public virtual ObjectResult<spGetCommunicationStage_Result> spGetCommunicationStage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCommunicationStage_Result>("spGetCommunicationStage");
        }
    
        public virtual ObjectResult<spGetFieldSite_Result> spGetFieldSite(string countryCode)
        {
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFieldSite_Result>("spGetFieldSite", countryCodeParameter);
        }
    
        public virtual ObjectResult<spSave_CommunityBasedComplaint_Result> spSave_CommunityBasedComplaint(Nullable<int> complaintID, string countryCode, string fieldSiteCode, Nullable<byte> complaintCategoryID, Nullable<byte> complaintClassificationID, Nullable<byte> complaintCommunicationMethodID, Nullable<byte> complaintStatusID, string donorCompanyCode, string projectIdentifier, Nullable<System.DateTime> submitDate, Nullable<System.DateTime> receivedDate, Nullable<int> receivedByEDWPersonID, Nullable<System.DateTime> enteredTimestamp, Nullable<int> enteredByEDWPersonID, Nullable<System.DateTime> closedDate, Nullable<int> closedByEDWPersonID, string complaintDescription, string otherComplaintCommunicationMethodText, string subjectText, Nullable<bool> acknowledgementProvidedFlag, Nullable<bool> appealedFlag, Nullable<bool> responseProvidedFlag, Nullable<bool> referralRequiredFlag, Nullable<byte> internalReferralLevelID, string noAcknowledgementReasonDescription, string noReferralReasonDescription, string noResponseReasonDescription, Nullable<bool> receivedByIMCStaffFlag, string receivedByNonIMCName, string responseByNonIMCName, string updateUser)
        {
            var complaintIDParameter = complaintID.HasValue ?
                new ObjectParameter("ComplaintID", complaintID) :
                new ObjectParameter("ComplaintID", typeof(int));
    
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            var fieldSiteCodeParameter = fieldSiteCode != null ?
                new ObjectParameter("FieldSiteCode", fieldSiteCode) :
                new ObjectParameter("FieldSiteCode", typeof(string));
    
            var complaintCategoryIDParameter = complaintCategoryID.HasValue ?
                new ObjectParameter("ComplaintCategoryID", complaintCategoryID) :
                new ObjectParameter("ComplaintCategoryID", typeof(byte));
    
            var complaintClassificationIDParameter = complaintClassificationID.HasValue ?
                new ObjectParameter("ComplaintClassificationID", complaintClassificationID) :
                new ObjectParameter("ComplaintClassificationID", typeof(byte));
    
            var complaintCommunicationMethodIDParameter = complaintCommunicationMethodID.HasValue ?
                new ObjectParameter("ComplaintCommunicationMethodID", complaintCommunicationMethodID) :
                new ObjectParameter("ComplaintCommunicationMethodID", typeof(byte));
    
            var complaintStatusIDParameter = complaintStatusID.HasValue ?
                new ObjectParameter("ComplaintStatusID", complaintStatusID) :
                new ObjectParameter("ComplaintStatusID", typeof(byte));
    
            var donorCompanyCodeParameter = donorCompanyCode != null ?
                new ObjectParameter("DonorCompanyCode", donorCompanyCode) :
                new ObjectParameter("DonorCompanyCode", typeof(string));
    
            var projectIdentifierParameter = projectIdentifier != null ?
                new ObjectParameter("ProjectIdentifier", projectIdentifier) :
                new ObjectParameter("ProjectIdentifier", typeof(string));
    
            var submitDateParameter = submitDate.HasValue ?
                new ObjectParameter("SubmitDate", submitDate) :
                new ObjectParameter("SubmitDate", typeof(System.DateTime));
    
            var receivedDateParameter = receivedDate.HasValue ?
                new ObjectParameter("ReceivedDate", receivedDate) :
                new ObjectParameter("ReceivedDate", typeof(System.DateTime));
    
            var receivedByEDWPersonIDParameter = receivedByEDWPersonID.HasValue ?
                new ObjectParameter("ReceivedByEDWPersonID", receivedByEDWPersonID) :
                new ObjectParameter("ReceivedByEDWPersonID", typeof(int));
    
            var enteredTimestampParameter = enteredTimestamp.HasValue ?
                new ObjectParameter("EnteredTimestamp", enteredTimestamp) :
                new ObjectParameter("EnteredTimestamp", typeof(System.DateTime));
    
            var enteredByEDWPersonIDParameter = enteredByEDWPersonID.HasValue ?
                new ObjectParameter("EnteredByEDWPersonID", enteredByEDWPersonID) :
                new ObjectParameter("EnteredByEDWPersonID", typeof(int));
    
            var closedDateParameter = closedDate.HasValue ?
                new ObjectParameter("ClosedDate", closedDate) :
                new ObjectParameter("ClosedDate", typeof(System.DateTime));
    
            var closedByEDWPersonIDParameter = closedByEDWPersonID.HasValue ?
                new ObjectParameter("ClosedByEDWPersonID", closedByEDWPersonID) :
                new ObjectParameter("ClosedByEDWPersonID", typeof(int));
    
            var complaintDescriptionParameter = complaintDescription != null ?
                new ObjectParameter("ComplaintDescription", complaintDescription) :
                new ObjectParameter("ComplaintDescription", typeof(string));
    
            var otherComplaintCommunicationMethodTextParameter = otherComplaintCommunicationMethodText != null ?
                new ObjectParameter("OtherComplaintCommunicationMethodText", otherComplaintCommunicationMethodText) :
                new ObjectParameter("OtherComplaintCommunicationMethodText", typeof(string));
    
            var subjectTextParameter = subjectText != null ?
                new ObjectParameter("SubjectText", subjectText) :
                new ObjectParameter("SubjectText", typeof(string));
    
            var acknowledgementProvidedFlagParameter = acknowledgementProvidedFlag.HasValue ?
                new ObjectParameter("AcknowledgementProvidedFlag", acknowledgementProvidedFlag) :
                new ObjectParameter("AcknowledgementProvidedFlag", typeof(bool));
    
            var appealedFlagParameter = appealedFlag.HasValue ?
                new ObjectParameter("AppealedFlag", appealedFlag) :
                new ObjectParameter("AppealedFlag", typeof(bool));
    
            var responseProvidedFlagParameter = responseProvidedFlag.HasValue ?
                new ObjectParameter("ResponseProvidedFlag", responseProvidedFlag) :
                new ObjectParameter("ResponseProvidedFlag", typeof(bool));
    
            var referralRequiredFlagParameter = referralRequiredFlag.HasValue ?
                new ObjectParameter("ReferralRequiredFlag", referralRequiredFlag) :
                new ObjectParameter("ReferralRequiredFlag", typeof(bool));
    
            var internalReferralLevelIDParameter = internalReferralLevelID.HasValue ?
                new ObjectParameter("InternalReferralLevelID", internalReferralLevelID) :
                new ObjectParameter("InternalReferralLevelID", typeof(byte));
    
            var noAcknowledgementReasonDescriptionParameter = noAcknowledgementReasonDescription != null ?
                new ObjectParameter("NoAcknowledgementReasonDescription", noAcknowledgementReasonDescription) :
                new ObjectParameter("NoAcknowledgementReasonDescription", typeof(string));
    
            var noReferralReasonDescriptionParameter = noReferralReasonDescription != null ?
                new ObjectParameter("NoReferralReasonDescription", noReferralReasonDescription) :
                new ObjectParameter("NoReferralReasonDescription", typeof(string));
    
            var noResponseReasonDescriptionParameter = noResponseReasonDescription != null ?
                new ObjectParameter("NoResponseReasonDescription", noResponseReasonDescription) :
                new ObjectParameter("NoResponseReasonDescription", typeof(string));
    
            var receivedByIMCStaffFlagParameter = receivedByIMCStaffFlag.HasValue ?
                new ObjectParameter("ReceivedByIMCStaffFlag", receivedByIMCStaffFlag) :
                new ObjectParameter("ReceivedByIMCStaffFlag", typeof(bool));
    
            var receivedByNonIMCNameParameter = receivedByNonIMCName != null ?
                new ObjectParameter("ReceivedByNonIMCName", receivedByNonIMCName) :
                new ObjectParameter("ReceivedByNonIMCName", typeof(string));
    
            var responseByNonIMCNameParameter = responseByNonIMCName != null ?
                new ObjectParameter("ResponseByNonIMCName", responseByNonIMCName) :
                new ObjectParameter("ResponseByNonIMCName", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CommunityBasedComplaint_Result>("spSave_CommunityBasedComplaint", complaintIDParameter, countryCodeParameter, fieldSiteCodeParameter, complaintCategoryIDParameter, complaintClassificationIDParameter, complaintCommunicationMethodIDParameter, complaintStatusIDParameter, donorCompanyCodeParameter, projectIdentifierParameter, submitDateParameter, receivedDateParameter, receivedByEDWPersonIDParameter, enteredTimestampParameter, enteredByEDWPersonIDParameter, closedDateParameter, closedByEDWPersonIDParameter, complaintDescriptionParameter, otherComplaintCommunicationMethodTextParameter, subjectTextParameter, acknowledgementProvidedFlagParameter, appealedFlagParameter, responseProvidedFlagParameter, referralRequiredFlagParameter, internalReferralLevelIDParameter, noAcknowledgementReasonDescriptionParameter, noReferralReasonDescriptionParameter, noResponseReasonDescriptionParameter, receivedByIMCStaffFlagParameter, receivedByNonIMCNameParameter, responseByNonIMCNameParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spSave_CBCResponseAppeal_Result> spSave_CBCResponseAppeal(Nullable<int> communityBasedComplaintID, Nullable<int> eDWPersonID, Nullable<System.DateTime> communicationDate, Nullable<byte> communicationStageID, Nullable<byte> communicationMethodID, string comment, string otherComplaintCommunicationMethodText, string updateUser)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var communicationDateParameter = communicationDate.HasValue ?
                new ObjectParameter("CommunicationDate", communicationDate) :
                new ObjectParameter("CommunicationDate", typeof(System.DateTime));
    
            var communicationStageIDParameter = communicationStageID.HasValue ?
                new ObjectParameter("CommunicationStageID", communicationStageID) :
                new ObjectParameter("CommunicationStageID", typeof(byte));
    
            var communicationMethodIDParameter = communicationMethodID.HasValue ?
                new ObjectParameter("CommunicationMethodID", communicationMethodID) :
                new ObjectParameter("CommunicationMethodID", typeof(byte));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var otherComplaintCommunicationMethodTextParameter = otherComplaintCommunicationMethodText != null ?
                new ObjectParameter("OtherComplaintCommunicationMethodText", otherComplaintCommunicationMethodText) :
                new ObjectParameter("OtherComplaintCommunicationMethodText", typeof(string));
    
            var updateUserParameter = updateUser != null ?
                new ObjectParameter("UpdateUser", updateUser) :
                new ObjectParameter("UpdateUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBCResponseAppeal_Result>("spSave_CBCResponseAppeal", communityBasedComplaintIDParameter, eDWPersonIDParameter, communicationDateParameter, communicationStageIDParameter, communicationMethodIDParameter, commentParameter, otherComplaintCommunicationMethodTextParameter, updateUserParameter);
        }
    
        public virtual ObjectResult<spGetvCommunityBasedComplaintDocumentation_Result> spGetvCommunityBasedComplaintDocumentation(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvCommunityBasedComplaintDocumentation_Result>("spGetvCommunityBasedComplaintDocumentation", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplaintLocation_Result> spEDITComplaintLocation(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintLocation_Result>("spEDITComplaintLocation", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplaintVulnerability_Result> spEDITComplaintVulnerability(Nullable<int> eDWComplainantID)
        {
            var eDWComplainantIDParameter = eDWComplainantID.HasValue ?
                new ObjectParameter("EDWComplainantID", eDWComplainantID) :
                new ObjectParameter("EDWComplainantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintVulnerability_Result>("spEDITComplaintVulnerability", eDWComplainantIDParameter);
        }
    
        public virtual ObjectResult<spEDITFieldSector_Result> spEDITFieldSector(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITFieldSector_Result>("spEDITFieldSector", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spGetCategory_Result> spGetCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCategory_Result>("spGetCategory");
        }
    
        public virtual ObjectResult<spGetFieldSiteDetails_Result> spGetFieldSiteDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFieldSiteDetails_Result>("spGetFieldSiteDetails");
        }
    
        public virtual ObjectResult<spEDITComplaintCommunication_Result> spEDITComplaintCommunication(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintCommunication_Result>("spEDITComplaintCommunication", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplaintResolution_Result> spEDITComplaintResolution(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintResolution_Result>("spEDITComplaintResolution", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spGetAppealCommitteNames_Result> spGetAppealCommitteNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAppealCommitteNames_Result>("spGetAppealCommitteNames");
        }
    
        public virtual ObjectResult<spEDITComplaintAppeal_Result> spEDITComplaintAppeal(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintAppeal_Result>("spEDITComplaintAppeal", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITExternalReferral_Result> spEDITExternalReferral(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITExternalReferral_Result>("spEDITExternalReferral", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplainantDetail_Result> spEDITComplainantDetail(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplainantDetail_Result>("spEDITComplainantDetail", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spUpdate_vCBCDocumentation_Result> spUpdate_vCBCDocumentation(Nullable<int> communityBasedComplaintDocID)
        {
            var communityBasedComplaintDocIDParameter = communityBasedComplaintDocID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintDocID", communityBasedComplaintDocID) :
                new ObjectParameter("CommunityBasedComplaintDocID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUpdate_vCBCDocumentation_Result>("spUpdate_vCBCDocumentation", communityBasedComplaintDocIDParameter);
        }
    
        public virtual ObjectResult<spUpdate_vCBCDocumentationAppeal_Result> spUpdate_vCBCDocumentationAppeal(Nullable<int> communityBasedComplaintDocID)
        {
            var communityBasedComplaintDocIDParameter = communityBasedComplaintDocID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintDocID", communityBasedComplaintDocID) :
                new ObjectParameter("CommunityBasedComplaintDocID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUpdate_vCBCDocumentationAppeal_Result>("spUpdate_vCBCDocumentationAppeal", communityBasedComplaintDocIDParameter);
        }
    
        public virtual ObjectResult<spGetFieldSiteByID_Result> spGetFieldSiteByID(string countryCode)
        {
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFieldSiteByID_Result>("spGetFieldSiteByID", countryCodeParameter);
        }
    
        public virtual ObjectResult<spEDITCommunityBasedComplaintDetails_Result> spEDITCommunityBasedComplaintDetails(Nullable<int> communityBasedComplaintID, string sDate, string eDate, string statusID, string countryCode)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            var sDateParameter = sDate != null ?
                new ObjectParameter("SDate", sDate) :
                new ObjectParameter("SDate", typeof(string));
    
            var eDateParameter = eDate != null ?
                new ObjectParameter("EDate", eDate) :
                new ObjectParameter("EDate", typeof(string));
    
            var statusIDParameter = statusID != null ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(string));
    
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITCommunityBasedComplaintDetails_Result>("spEDITCommunityBasedComplaintDetails", communityBasedComplaintIDParameter, sDateParameter, eDateParameter, statusIDParameter, countryCodeParameter);
        }
    
        public virtual ObjectResult<spDelete_CBCDetails_Result> spDelete_CBCDetails(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBCDetails_Result>("spDelete_CBCDetails", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplaintCommunicationACK_Result> spEDITComplaintCommunicationACK(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintCommunicationACK_Result>("spEDITComplaintCommunicationACK", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplaintCommunicationAR_Result> spEDITComplaintCommunicationAR(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintCommunicationAR_Result>("spEDITComplaintCommunicationAR", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplaintCommunicationFR_Result> spEDITComplaintCommunicationFR(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintCommunicationFR_Result>("spEDITComplaintCommunicationFR", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITComplaintCommunicationHQ_Result> spEDITComplaintCommunicationHQ(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITComplaintCommunicationHQ_Result>("spEDITComplaintCommunicationHQ", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spGetvProjectByID_Result> spGetvProjectByID(string countryCode)
        {
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetvProjectByID_Result>("spGetvProjectByID", countryCodeParameter);
        }
    
        public virtual ObjectResult<spEDITAppealCommittee_Result> spEDITAppealCommittee(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITAppealCommittee_Result>("spEDITAppealCommittee", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spEDITAppealCommittee2_Result> spEDITAppealCommittee2(Nullable<int> communityBasedComplaintID)
        {
            var communityBasedComplaintIDParameter = communityBasedComplaintID.HasValue ?
                new ObjectParameter("CommunityBasedComplaintID", communityBasedComplaintID) :
                new ObjectParameter("CommunityBasedComplaintID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITAppealCommittee2_Result>("spEDITAppealCommittee2", communityBasedComplaintIDParameter);
        }
    
        public virtual ObjectResult<spDelete_CBFAdminGroup_Result> spDelete_CBFAdminGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFAdminGroup_Result>("spDelete_CBFAdminGroup");
        }
    
        public virtual ObjectResult<spSave_CBFAdminGroup_Result> spSave_CBFAdminGroup(Nullable<int> eDWPersonID)
        {
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBFAdminGroup_Result>("spSave_CBFAdminGroup", eDWPersonIDParameter);
        }
    
        public virtual ObjectResult<spEDITAdminGroup_Result> spEDITAdminGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITAdminGroup_Result>("spEDITAdminGroup");
        }
    
        public virtual ObjectResult<spDelete_CBFITGroup_Result> spDelete_CBFITGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFITGroup_Result>("spDelete_CBFITGroup");
        }
    
        public virtual ObjectResult<spEDITITGroup_Result> spEDITITGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITITGroup_Result>("spEDITITGroup");
        }
    
        public virtual ObjectResult<spSave_CBFITGroup_Result> spSave_CBFITGroup(Nullable<int> eDWPersonID)
        {
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBFITGroup_Result>("spSave_CBFITGroup", eDWPersonIDParameter);
        }
    
        public virtual ObjectResult<spDelete_CBFHQGroup_Result> spDelete_CBFHQGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFHQGroup_Result>("spDelete_CBFHQGroup");
        }
    
        public virtual ObjectResult<spEDITHQGroup_Result> spEDITHQGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITHQGroup_Result>("spEDITHQGroup");
        }
    
        public virtual ObjectResult<spSave_CBFHQGroup_Result> spSave_CBFHQGroup(Nullable<int> eDWPersonID)
        {
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBFHQGroup_Result>("spSave_CBFHQGroup", eDWPersonIDParameter);
        }
    
        public virtual ObjectResult<spEDITMealCordinator_Result> spEDITMealCordinator()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEDITMealCordinator_Result>("spEDITMealCordinator");
        }
    
        public virtual ObjectResult<spSave_CBFMealCordinator_Result> spSave_CBFMealCordinator(Nullable<int> eDWPersonID, string countryCode)
        {
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBFMealCordinator_Result>("spSave_CBFMealCordinator", eDWPersonIDParameter, countryCodeParameter);
        }
    
        public virtual ObjectResult<spDelete_CBFMealCordinator_Result> spDelete_CBFMealCordinator(string countryCode)
        {
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("countryCode", countryCode) :
                new ObjectParameter("countryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFMealCordinator_Result>("spDelete_CBFMealCordinator", countryCodeParameter);
        }
    
        public virtual ObjectResult<spMealCordinator_Result> spMealCordinator(string countrycode)
        {
            var countrycodeParameter = countrycode != null ?
                new ObjectParameter("countrycode", countrycode) :
                new ObjectParameter("countrycode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMealCordinator_Result>("spMealCordinator", countrycodeParameter);
        }
    
        public virtual ObjectResult<spDelete_CBFOfficers_Result> spDelete_CBFOfficers(string countryCode)
        {
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("countryCode", countryCode) :
                new ObjectParameter("countryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDelete_CBFOfficers_Result>("spDelete_CBFOfficers", countryCodeParameter);
        }
    
        public virtual ObjectResult<spEditOfficer_Result> spEditOfficer(string countrycode)
        {
            var countrycodeParameter = countrycode != null ?
                new ObjectParameter("countrycode", countrycode) :
                new ObjectParameter("countrycode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEditOfficer_Result>("spEditOfficer", countrycodeParameter);
        }
    
        public virtual ObjectResult<spSave_CBFOfficer_Result> spSave_CBFOfficer(Nullable<int> eDWPersonID, string countryCode, string fieldSiteName)
        {
            var eDWPersonIDParameter = eDWPersonID.HasValue ?
                new ObjectParameter("EDWPersonID", eDWPersonID) :
                new ObjectParameter("EDWPersonID", typeof(int));
    
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            var fieldSiteNameParameter = fieldSiteName != null ?
                new ObjectParameter("FieldSiteName", fieldSiteName) :
                new ObjectParameter("FieldSiteName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_CBFOfficer_Result>("spSave_CBFOfficer", eDWPersonIDParameter, countryCodeParameter, fieldSiteNameParameter);
        }
    
        public virtual ObjectResult<spGetCountriesforUserManager_Result> spGetCountriesforUserManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCountriesforUserManager_Result>("spGetCountriesforUserManager");
        }
    }
}
