//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBFRM.Areas.ComplainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCommunityBasedComplaint
    {
        public int CommunityBasedComplaintID { get; set; }
        public string CountryCode { get; set; }
        public Nullable<short> FacilityID { get; set; }
        public string FieldSiteCode { get; set; }
        public Nullable<byte> ComplaintCategoryID { get; set; }
        public Nullable<byte> ComplaintClassificationID { get; set; }
        public Nullable<byte> ComplaintCommunicationMethodID { get; set; }
        public byte ComplaintStatusID { get; set; }
        public string DonorCompanyCode { get; set; }
        public string DonorIdentifier { get; set; }
        public string ProjectIdentifier { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public Nullable<int> ReceivedByEDWPersonID { get; set; }
        public string ReceivedByNonIMCName { get; set; }
        public string ResponseByNonIMCName { get; set; }
        public System.DateTime EnteredTimestamp { get; set; }
        public int EnteredByEDWPersonID { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> ClosedByEDWPersonID { get; set; }
        public string ComplaintDescription { get; set; }
        public string OtherComplaintCommunicationMethodText { get; set; }
        public string SubjectText { get; set; }
        public Nullable<bool> AcknowledgementProvidedFlag { get; set; }
        public Nullable<bool> AppealedFlag { get; set; }
        public Nullable<bool> ReceivedByIMCStaffFlag { get; set; }
        public Nullable<bool> ResponseProvidedFlag { get; set; }
        public Nullable<bool> ReferralRequiredFlag { get; set; }
        public Nullable<byte> ReferralTypeID { get; set; }
        public Nullable<byte> InternalReferralLevelID { get; set; }
        public string NoAcknowledgementReasonDescription { get; set; }
        public string NoReferralReasonDescription { get; set; }
        public string NoResponseReasonDescription { get; set; }
        public string UpdateUser { get; set; }
        public bool SourceDeletedFlag { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime LastUpdateTimestamp { get; set; }
        public string LastUpdateUser { get; set; }
    }
}
