//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBFRM.Areas.ComplainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vComplaintCommunication
    {
        public int CommunityBasedComplaintID { get; set; }
        public int EDWPersonID { get; set; }
        public System.DateTime CommunicationDate { get; set; }
        public byte CommunicationStageID { get; set; }
        public Nullable<byte> CommunicationMethodID { get; set; }
        public string Comment { get; set; }
        public string UpdateUser { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime LastUpdateTimestamp { get; set; }
        public string LastUpdateUser { get; set; }
        public string OtherComplaintCommunicationMethodText { get; set; }
        public bool FromPersonFlag { get; set; }
    }
}
