//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBFRM.Areas.ComplainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCommunicationStage
    {
        public byte CommunicationStageID { get; set; }
        public string CommunicationStageName { get; set; }
        public string CommunicationStageShortName { get; set; }
        public Nullable<byte> ReminderDayCount { get; set; }
        public short DisplaySequenceNumber { get; set; }
    }
}
