//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBFRM.Areas.ComplainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDonor_Name
    {
        public string CompanyCode { get; set; }
        public string DonorIdentifier { get; set; }
        public string DonorName { get; set; }
        public string DonorShortName { get; set; }
        public string DonorTypeCode { get; set; }
        public string DonorCategoryCode { get; set; }
    }
}
