//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBFRM.Areas.ComplainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLanguageDialect
    {
        public string LanguageDialectCode { get; set; }
        public string LanguageName { get; set; }
        public string LanguageShortName { get; set; }
        public string ISOLanguageCode { get; set; }
        public string DialectName { get; set; }
        public short DisplaySequenceNumber { get; set; }
    }
}
