//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBFRM.Areas.ComplainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSex
    {
        public string SexCode { get; set; }
        public string SexName { get; set; }
        public string SexShortName { get; set; }
        public short DisplaySequenceNumber { get; set; }
    }
}
